### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kFxDaKing** [Sn0wBiT/esx_tpnrp_teamdeathmatch#1]
es_extended: TriggerServerCallback => [esx_tpnrp_teamdeathmatch:getStatus] does not exist

**Comment by kFxDaKing** [comment]
I think i fixed that, but there is no marker to enter the arena.

Also there is missing png images in html/index_files.

**Comment by Sn0wBiT** [comment]
You need to set this in server.lua to enable game.
```
isEnableMatch = true
```
I fixed. Please update again!
P/s: If you love this please let a star for this! Thank you.
