### ISSUE TITLE
No marker to join arena

### ISSUE THREAD

**Issue by kFxDaKing** [Sn0wBiT/esx_tpnrp_teamdeathmatch#2]
Hello, there isnt any errors, but when i teleport to arena blip, there is not marker to join arena.

**Comment by kFxDaKing** [comment]
https://streamable.com/qsx61x

**Comment by Sn0wBiT** [comment]
You need to set this in server.lua
```
isEnableMatch = true
```

**Comment by kFxDaKing** [comment]
Yep, that works.

**Comment by kFxDaKing** [comment]
Another bug, when you win the round, all players are randomly spawned around the arena, instead in their base.

**Comment by kFxDaKing** [comment]
Can iget your discord please?

**Comment by Sn0wBiT** [comment]
Leopold #6615

**Comment by kFxDaKing** [comment]
Added

**Comment by Sn0wBiT** [comment]
You need to updated newest version.
